- command: hostname
  register: hostname
- set_fact:
    hostname={{ hostname.stdout }}

- name: Create client configs directory
  shell: mkdir -p {{ client_configs_dir }}/keys
  args:
    creates: '{{ client_configs_dir }}'

- name: Set client configs directory permisssions
  command: chmod -R 700 {{ client_configs_dir }}

# echo to specify CN in order to avoid one client disconnecting others
- name: Create client keys
  shell: echo {{ item.name }} | ./easyrsa gen-req {{ item.name }} nopass
  args:
    chdir: '{{ server_base_dir }}'
    creates: '{{ server_pki_dir }}/private/{{ item.name }}.key'
  with_items: '{{ clients }}'

- name: Copy client keys to client configs directory
  shell: cp {{ server_pki_dir }}/private/{{ item.name }}.key {{ client_configs_dir }}/keys/
  args:
    creates: '{{ client_configs_dir }}/keys/{{ item.name }}.key'
  with_items: '{{ clients }}'

- name: Copy client CSR to CA
  shell: scp {{ server_pki_dir }}/reqs/{{ item.name }}.req {{ ca_host }}:/tmp
  with_items: '{{ clients }}'

- name: Import client CSR to CA
  shell: export EASYRSA_BATCH=1 && ./easyrsa import-req /tmp/{{ item.name }}.req {{ item.name }}
  args:
    chdir: '{{ ca_base_dir }}'
    creates: '{{ ca_pki_dir }}/reqs/{{ item.name }}.req'
  with_items: '{{ clients }}'
  delegate_to: '{{ ca_host }}'

- name: Sign client CSR by CA
  shell: export EASYRSA_BATCH=1 && ./easyrsa sign-req client {{ item.name }}
  args:
    chdir: '{{ ca_base_dir }}'
    creates: '{{ ca_pki_dir }}/issued/{{ item.name }}.crt'
  with_items: '{{ clients }}'
  delegate_to: '{{ ca_host }}'

- name: Copy signed client certificate to server
  shell: scp {{ remote_ca_pki_dir }}/issued/{{ item.name }}.crt /tmp
  with_items: '{{ clients }}'

- name: Copy signed client certificate to client configs directory
  shell: cp /tmp/{{ item.name }}.crt {{ client_configs_dir }}/keys/
  with_items: '{{ clients }}'

- name: Copy ta.key to client configs directory
  shell: cp {{ server_base_dir }}/ta.key {{ client_configs_dir }}/keys/
  args:
    creates: '{{ client_configs_dir }}/keys/ta.key'

- name: Copy ca.crt to client configs directory
  become: true
  shell: cp /etc/openvpn/server/ca.crt {{ client_configs_dir }}/keys/
  args:
    creates: '{{ client_configs_dir }}/keys/ca.crt'

- name: Set owner of ca.crt
  become: true
  shell: chown ubuntu:ubuntu {{ client_configs_dir }}/keys/ca.crt
